adresses:
        - "https://emberger.xyz/index.xml"
        - "https://martinfowler.com/feed.atom"
articlenumber: 10
title: "Ember's Feed Aggregator"
useragent: "KikiFeedService https://github.com/Elesh-Norn/KikiFeedService rss feed aggregator"
